"""add base_url col to members table

Revision ID: 38a9c73bfce2
Revises: 6e7c33ddf30f
Create Date: 2024-07-29 15:18:15.979804

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '38a9c73bfce2'
down_revision = '6e7c33ddf30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'base_url')
    # ### end Alembic commands ###