"""Add managed col in skills table

Revision ID: a8fff9df0a02
Revises: 6fa42be09dd2
Create Date: 2024-06-13 12:17:08.622973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fff9df0a02'
down_revision = '6fa42be09dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('managed', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    # ### end Alembic commands ###

    # Remove server default after setting the initial values
    op.alter_column('skill', 'managed', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'managed')
    # ### end Alembic commands ###