"""add worfklow column

Revision ID: b922e3e826e9
Revises: 634ddcf1c767
Create Date: 2024-05-07 14:28:12.169813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b922e3e826e9'
down_revision = '634ddcf1c767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('workflow', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'workflow')
    # ### end Alembic commands ###
