"""Add thread table

Revision ID: ec7fa327dfa7
Revises: 3b4636df4c6d
Create Date: 2024-05-25 09:35:50.607171

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec7fa327dfa7'
down_revision = '3b4636df4c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('thread_ts', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_ts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'thread_ts', name='checkpoints_pkey')
    )
    op.drop_table('thread')
    # ### end Alembic commands ###
